/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:808014:
  appc.background(230);
} //_CODE_:window1:808014:

public void Pencil_click(GButton source, GEvent event) { //_CODE_:Pencil:261240:
  println("Pencil selected");
} //_CODE_:Pencil:261240:

public void Marker_click(GButton source, GEvent event) { //_CODE_:Marker:809047:
  println("Marker selected");
} //_CODE_:Marker:809047:

public void thickness_change(GCustomSlider source, GEvent event) { //_CODE_:thickness:942316:
  brushSize = thickness.getValueF();
} //_CODE_:thickness:942316:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  Pencil = new GButton(window1, 20, 13, 80, 30);
  Pencil.setText("Pencil");
  Pencil.addEventHandler(this, "Pencil_click");
  Marker = new GButton(window1, 137, 13, 80, 30);
  Marker.setText("Marker");
  Marker.addEventHandler(this, "Marker_click");
  thickness = new GCustomSlider(window1, 69, 55, 100, 40, "grey_blue");
  thickness.setShowValue(true);
  thickness.setLimits(20.0, 0.1, 50.0);
  thickness.setNbrTicks(5);
  thickness.setShowTicks(true);
  thickness.setNumberFormat(G4P.DECIMAL, 2);
  thickness.setOpaque(false);
  thickness.addEventHandler(this, "thickness_change");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton Pencil; 
GButton Marker; 
GCustomSlider thickness; 
