/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:Settings:808014:
  appc.background(230);
} //_CODE_:Settings:808014:

public void PencilButtonClick(GButton source, GEvent event) { //_CODE_:PencilButton:261240:
  currentTool = new PencilTool(brushSize, currentColor);
} //_CODE_:PencilButton:261240:

public void EraserButtonClick(GButton source, GEvent event) { //_CODE_:EraserButton:809047:
  currentTool = new EraserTool(brushSize, color(255));
} //_CODE_:EraserButton:809047:

public void ToolSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:ToolSlider:942316:
  brushSize = ToolSlider.getValueF();
  if(currentTool != null){
    currentTool.toolSize = brushSize;
  }
} //_CODE_:ToolSlider:942316:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Settings = GWindow.getWindow(this, "Settings", 0, 0, 240, 120, JAVA2D);
  Settings.noLoop();
  Settings.setActionOnClose(G4P.KEEP_OPEN);
  Settings.addDrawHandler(this, "win_draw1");
  PencilButton = new GButton(Settings, 20, 15, 80, 30);
  PencilButton.setText("Pencil");
  PencilButton.addEventHandler(this, "PencilButtonClick");
  EraserButton = new GButton(Settings, 140, 15, 80, 30);
  EraserButton.setText("Eraser");
  EraserButton.addEventHandler(this, "EraserButtonClick");
  ToolSlider = new GCustomSlider(Settings, 68, 55, 100, 40, "grey_blue");
  ToolSlider.setShowValue(true);
  ToolSlider.setLimits(15.0, 0.1, 50.0);
  ToolSlider.setNbrTicks(5);
  ToolSlider.setShowTicks(true);
  ToolSlider.setNumberFormat(G4P.DECIMAL, 2);
  ToolSlider.setOpaque(false);
  ToolSlider.addEventHandler(this, "ToolSliderChanged");
  Settings.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow Settings;
GButton PencilButton; 
GButton EraserButton; 
GCustomSlider ToolSlider; 
